### PR TITLE
Misc. typo fixes

### PR DESCRIPTION
**Pull request by luzpaz**
contains user-facing and non-user facing typo fixes. Found via `codespell -q 3`.
Branched off of branch `0.1.0`

### CODE REVIEW

**Comment by hanakin** [comment]
Thanks for point these out, unfortunately I will have to break this up as several of these changes affect base-l which is part of the new base branch

**Comment by hanakin** [comment]
Ok fixed all the base-l related typos can you please rebase

**Comment by luzpaz** [comment]
@hanakin where should I rebase them on?

**Comment by hanakin** [comment]
Rebase to fix the merge conflicts on the current branch

**Comment by luzpaz** [comment]
@hanakin done (2c591b0)

**Comment by hanakin** [comment]
sorry to ask but never got around to doing it. I changed the base to master... can you please rebase on master as it should be up to date

**Comment by luzpaz** [comment]
yikes :fearful:

**Comment by luzpaz** [comment]
Closing in favor of #58

**Pull request closed without merging**
